// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleBotFramework.Db.BroadcastDb;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MultipleBotFramework.Db.BroadcastDb.Migrations
{
    [DbContext(typeof(BroadcastDbContext))]
    [Migration("20250326152206_AddBotIdField")]
    partial class AddBotIdField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MultipleBotFramework.Db.BroadcastDb.Entity.BroadcastMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BotId")
                        .HasColumnType("bigint")
                        .HasColumnName("bot_id");

                    b.Property<long>("BroadcastTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("broadcast_task_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("text")
                        .HasColumnName("error_log");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_broadcast_messages");

                    b.HasIndex("BroadcastTaskId")
                        .HasDatabaseName("ix_broadcast_messages_broadcast_task_id");

                    b.ToTable("broadcast_messages", "broadcast");
                });

            modelBuilder.Entity("MultipleBotFramework.Db.BroadcastDb.Entity.BroadcastTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("Идентификатор сущности.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bot_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("FromChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_chat_id");

                    b.Property<int>("FromMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("from_message_id");

                    b.Property<string>("MediaFileId")
                        .HasColumnType("text")
                        .HasColumnName("media_file_id");

                    b.Property<string>("ReplyMarkupJson")
                        .HasColumnType("text")
                        .HasColumnName("reply_markup_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_broadcast_tasks");

                    b.ToTable("broadcast_tasks", "broadcast");
                });

            modelBuilder.Entity("MultipleBotFramework.Db.BroadcastDb.Entity.BroadcastMessage", b =>
                {
                    b.HasOne("MultipleBotFramework.Db.BroadcastDb.Entity.BroadcastTask", "BroadcastTask")
                        .WithMany("Messages")
                        .HasForeignKey("BroadcastTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_broadcast_messages_broadcast_tasks_broadcast_task_id");

                    b.Navigation("BroadcastTask");
                });

            modelBuilder.Entity("MultipleBotFramework.Db.BroadcastDb.Entity.BroadcastTask", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
