<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Burtimax.TelegramBot.MultipleBotFramework.Endpoints</PackageId>
        <Description>Эндпоинты для телеграм бота.</Description>
        <RepositoryUrl>https://github.com/burtimax/BotTemplateWebApi</RepositoryUrl>
        <PackageTags>endpoints telegram bot telegrambot framework</PackageTags>
        <PackageVersion>2.1.0</PackageVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Burtimax.TelegramBot.MultipleBotFramework" Version="1.0.4" />
      <PackageReference Include="FastEndpoints" Version="5.29.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Enpdoints\Common\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MultipleBotFramework\MultipleBotFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="README.md">
        <Pack>true</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Update="MIT License.txt">
        <Pack>true</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
